# Generated by Django 2.0.3 on 2018-03-14 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OTCBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otc', models.UUIDField(default=uuid.uuid4, verbose_name='UUID code')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='created in')),
                ('used_in', models.DateTimeField(blank=True, null=True, verbose_name='used in')),
                ('is_used', models.BooleanField(default=False, verbose_name='is used')),
            ],
        ),
        migrations.CreateModel(
            name='OTCRegistration',
            fields=[
                ('otcbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='OTC.OTCBase')),
                ('link', models.CharField(blank=True, max_length=256, verbose_name='link')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_otc', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('OTC.otcbase',),
        ),
    ]
