# Generated by Django 2.0.3 on 2018-03-14 18:20

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OTC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationTry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=60)),
                ('extra_data', models.TextField(blank=True, null=True)),
                ('created_in', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('finished_in', models.DateTimeField(blank=True, null=True)),
                ('otc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_otc', to='OTC.OTCRegistration')),
            ],
        ),
    ]
